services:
  app:
    build: .
    ports:
      - "8000:80"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
    networks:
      - recipe-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - recipe-network

volumes:
  redis-data:

networks:
  recipe-network:
    driver: bridge
